name: rescuerun
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.2.0
  toggle_switch: ^2.1.0
  easy_search_bar: ^2.5.0

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.6.7

  # Location & Maps
  geolocator: ^10.1.0
  geocoding: ^2.2.0
  google_maps_flutter: ^2.5.3
  permission_handler: ^11.3.0

  # Utilities
  uuid: ^4.0.0
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  image_picker: ^0.8.7+1
  url_launcher: ^6.2.6
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
