// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5x8KbCVAh1LpISkZ9LCPKMLvjnKEJ3iQ',
    appId: '1:796765349899:web:f87e5469a1142f52af7f0e',
    messagingSenderId: '796765349899',
    projectId: 'rescue-run-project',
    authDomain: 'rescue-run-project.firebaseapp.com',
    storageBucket: 'rescue-run-project.firebasestorage.app',
    measurementId: 'G-834D5HBJC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4bkDr14ZHKMGMK5sbgrafx0ThZO9BD8o',
    appId: '1:796765349899:android:e9e7b327c0f31d49af7f0e',
    messagingSenderId: '796765349899',
    projectId: 'rescue-run-project',
    storageBucket: 'rescue-run-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_dYwa3m-Iq8oNKbLKONzXAQz2S8iD3ow',
    appId: '1:796765349899:ios:ba22848ea8942ae6af7f0e',
    messagingSenderId: '796765349899',
    projectId: 'rescue-run-project',
    storageBucket: 'rescue-run-project.firebasestorage.app',
    iosBundleId: 'com.example.rescuerun',
  );
}
